--- #YAML:1.0
name:               Data-Dump-Streamer
version:            2.11
abstract:           Accurately serialize a data structure as Perl code.
author:
    - Yves Orton (demerphq)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Deparse:      0
    B::Utils:        0.05
    Test::More:      0
    Text::Abbrev:    0
    Text::Balanced:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
