# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Dump-Streamer
version:      1.12
version_from: lib/Data/Dump/Streamer.pm
installdirs:  site
requires:
    B::Deparse:                    
    B::Utils:                      
    Test::More:                    
    Text::Balanced:                

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
