# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Dump-Streamer
version:      1.14
version_from: lib/Data/Dump/Streamer.pm
installdirs:  site
requires:
    B::Deparse:                    0
    B::Utils:                      0
    Test::More:                    0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
