--- #YAML:1.0
name:                Data-Dump-Streamer
version:             2.07-39
abstract:            Accurately serialize a data structure as Perl code.
license:             ~
author:              
    - Yves Orton (demerphq)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    B::Deparse:                    0
    B::Utils:                      0.05
    Test::More:                    0
    Text::Abbrev:                  0
    Text::Balanced:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
