# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Dump-Streamer
version:      2.03-30
version_from: 
installdirs:  site
requires:
    B::Deparse:                    0
    B::Utils:                      0.05
    Test::More:                    0
    Text::Abbrev:                  0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
