# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Dump-Streamer
version:      1.07
version_from: lib/Data/Dump/Streamer.pm
installdirs:  site
requires:
    Algorithm::Diff:               1.15
    Data::Dumper:                  2.121
    Test::More:                    
    Text::Balanced:                1.95

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
